### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by SolarAquarion** [talisein/mal-gtk#4]
In file included from main.cpp:22:0:
application.hpp: In function ‘int main(int, char**)’:
application.hpp:24:8: error: inlining failed in call to ‘MAL::Application::~Application() noexcept’: call is unlikely and code size would grow [-Werror=inline]
  class Application
        ^
main.cpp:33:36: error: called from here [-Werror=inline]
     MAL::Application app(argc, argv);
                                    ^
In file included from main.cpp:22:0:
application.hpp:24:8: error: inlining failed in call to ‘MAL::Application::~Application() noexcept’: call is unlikely and code size would grow [-Werror=inline]
  class Application
        ^
main.cpp:33:36: error: called from here [-Werror=inline]
     MAL::Application app(argc, argv);
                                    ^
cc1plus: all warnings being treated as errors
Makefile:658: recipe for target 'mal_gtk-main.o' failed

**Comment by talisein** [comment]
Hello, thank you for the report. What compiler and version were you using? Also your distro will probably be helpful.

**Comment by SolarAquarion** [comment]
GCC5 latest version.  Arch Linux

**Comment by talisein** [comment]
It compiles fine on gcc 5.3.1. Arch is too much of a time sink for me to try and install and debug. mal-gtk is not really ready for public consumption anyways, so I guess you're out of luck. Thanks for the report though.
